version: '3.7'
services:
  elasticbeanstalkonrails:
    working_dir: $PWD
    build:
      context: .
      target: builder
      args:
        RAILS_ENV: development
    env_file:
      - ./.env
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:$PWD
      - elasticbeanstalkonrails:/home/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:4.0.6-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
volumes:
  elasticbeanstalkonrails:
  postgres:
  redis:
